/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Enum.java.enum.vm
 */
package com.mycompany.myapp.domain;

public enum Role {
    ROLE_ADMIN("ADMIN", "Администратор"), //
    ROLE_PRESENTER("PRESENTER", "Докладчик"), //
    ROLE_LISTENER("LISTENER", "Слушатель");

    private final String value;
    private final String displayName;

    /**
     * @param value       The value that is persisted in the database.
     * @param displayName
     */
    Role(String value, String displayName) {
        this.value = value;
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    /**
     * @return the value that is persisted in the database.
     */
    public String getValue() {
        return value;
    }

    /**
     * @return the Role instance having its value matching exactly the passed value.
     */
    public static Role fromValue(String value) {
        if (value == null) {
            return null;
        }
        for (Role e : Role.values()) {
            if (value.equals(e.getValue())) {
                return e;
            }
        }
        return null;
    }
}