/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Simple DTO for Presentation.
 */
public class PresentationDTO /*implements Identifiable<Integer>, Serializable */{
    private static final Logger log = Logger.getLogger(PresentationDTO.class.getName());
    public Integer id;
    @NotEmpty
    @NotNull
    @Size(min=4, max=200)
    public String title;
    public Set<UserDTO> presenters = new HashSet<>();

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Set<UserDTO> getPresenters() {
        return presenters;
    }

    public void setPresenters(Set<UserDTO> presenters) {
        this.presenters = presenters;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PresentationDTO that = (PresentationDTO) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public PresentationDTO title(String title) {
        this.title = title;
        return this;
    }

    public PresentationDTO addPresenter(UserDTO user) {
        presenters.add(user);
        return this;
    }
}