/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.mycompany.myapp.domain.Room;
import org.springframework.stereotype.Service;

/**
 * A simple DTO Facility for Room.
 */
@Service
public class RoomDTOService {

    /**
     * Converts the passed room to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *  @param room
     *
     */
    public RoomDTO toDTO(Room room) {
        if (room == null) {
            return null;
        }

        RoomDTO dto = new RoomDTO();

        dto.id = room.getId();
        dto.roomNumber = room.getRoomNumber();

        return dto;
    }

    /**
     * Converts the passed dto to a Room.
     * Convenient for query by example.
     */
    public Room toEntity(RoomDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        Room room = new Room();

        room.setId(dto.id);
        room.setRoomNumber(dto.roomNumber);
        if (depth-- > 0) {
        }

        return room;
    }
}