/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.logging.Logger;

/**
 * Simple DTO for Schedule.
 */
public class ScheduleDTO {
    private static final Logger log = Logger.getLogger(ScheduleDTO.class.getName());
    public Integer id;
    @NotNull
    public LocalDateTime eventTime;
    @NotNull
    @Min(10)
    @Max(180)
    public Integer eventDurationMin;
    @Valid
    public RoomDTO room;
    @Valid
    public PresentationDTO presentation;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDateTime getEventTime() {
        return eventTime;
    }

    public void setEventTime(LocalDateTime eventTime) {
        this.eventTime = eventTime;
    }

    public Integer getEventDurationMin() {
        return eventDurationMin;
    }

    public void setEventDurationMin(Integer eventDurationMin) {
        this.eventDurationMin = eventDurationMin;
    }

    public RoomDTO getRoom() {
        return room;
    }

    public void setRoom(RoomDTO room) {
        this.room = room;
    }

    public PresentationDTO getPresentation() {
        return presentation;
    }

    public void setPresentation(PresentationDTO presentation) {
        this.presentation = presentation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ScheduleDTO that = (ScheduleDTO) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

}